name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - '**/*.md'

jobs:
  build:
    name: 🦥 Brew .Sloth installation
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set current repository for pull requests
        run: |
          echo "PR_REPOSITORY=${{ github.event.pull_request.head.repo.full_name }}" >> $GITHUB_ENV

      - name: Set current env
        run: echo "ENV=CI" >> $GITHUB_ENV

      - name: Set no analytics for homebre
        run: echo "HOMEBREW_NO_ANALYTICS=true" >> $GITHUB_ENV

      - name: Install brew linux
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install build-essential procps curl file git

      - name: Install brew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Finish installation on Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          test -x ~/.linuxbrew/bin/brew && eval $(~/.linuxbrew/bin/brew shellenv)
          test -x /home/linuxbrew/.linuxbrew/bin/brew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
          command -v brew &> /dev/null && eval "$(brew --prefix)/bin/brew shellenv"

      - name: Install .Sloth
        run: |
          brew install --include-test --formula Formula/dot.rb
          
      - name: Check .Sloth is installed
        run: |
          brew tap gtrabanco/tools
          brew list gtrabanco/tools/dot
